// Create web server
// npm install express
// npm install body-parser
// npm install mongoose
// npm install ejs
// npm install express-sanitizer
// npm install method-override
// npm install passport
// npm install passport-local
// npm install passport-local-mongoose
// npm install express-session
// npm install connect-flash
// npm install connect-mongo
// npm install express-validator
// npm install express-mongo-sanitize
// npm install helmet
// npm install compression
// npm install morgan
// npm install multer
// npm install cloudinary
// npm install cloudinary-core